#include "CavaService.h"

#include <QDir>
#include <QFileInfo>
#include <QProcess>
#include <QSaveFile>
#include <QStandardPaths>

namespace vespera {

CavaService::CavaService(QObject *parent) : QObject(parent) {
    m_available = !QStandardPaths::findExecutable(QStringLiteral("cava")).isEmpty();
    m_bars.reserve(m_barCount);
    for (int i = 0; i < m_barCount; ++i) m_bars.append(0);

    QString base = QStandardPaths::writableLocation(QStandardPaths::AppConfigLocation);
    if (base.isEmpty()) base = QDir::homePath() + QStringLiteral("/.config/vespera");
    m_configPath = base + QStringLiteral("/cava_raw.conf");
}

CavaService::~CavaService() { stop(); }

void CavaService::setActive(bool value) {
    if (m_demo) return;  // demo spectrum is frozen; don't spawn cava
    if (m_active == value) return;
    m_active = value;
    emit activeChanged();
    if (m_active && m_available)
        start();
    else
        stop();
}

void CavaService::loadDemo() {
    m_demo = true;
    stop();
    // a pleasing, symmetric-ish frozen spectrum
    static const int pattern[44] = {14, 22, 31, 40, 52, 63, 71, 78, 84, 76, 68, 60, 55, 62, 70,
                                    58, 47, 41, 49, 57, 66, 74, 80, 72, 63, 54, 60, 68, 61, 52,
                                    45, 51, 59, 67, 58, 48, 39, 33, 40, 34, 27, 21, 16, 11};
    for (int i = 0; i < m_barCount && i < 44; ++i) m_bars[i] = pattern[i];
    emit barsChanged();
}

void CavaService::writeConfig() {
    QDir().mkpath(QFileInfo(m_configPath).absolutePath());
    QSaveFile f(m_configPath);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Truncate)) return;
    const QByteArray cfg =
        "# generated by vespera — raw ascii visualizer stream\n"
        "[general]\n"
        "bars = 44\n"
        "framerate = 60\n"
        "sleep_timer = 3\n"
        "[input]\n"
        "method = pulse\n"
        "[output]\n"
        "method = raw\n"
        "raw_target = /dev/stdout\n"
        "data_format = ascii\n"
        "ascii_max_range = 100\n"
        "[smoothing]\n"
        "monstercat = 1\n"
        "noise_reduction = 70\n";
    f.write(cfg);
    f.commit();
}

void CavaService::start() {
    if (m_proc) return;
    writeConfig();
    m_proc = new QProcess(this);
    m_proc->setProcessChannelMode(QProcess::SeparateChannels);
    connect(m_proc, &QProcess::readyReadStandardOutput, this, &CavaService::onReadyRead);
    m_proc->start(QStringLiteral("cava"), {QStringLiteral("-p"), m_configPath});
}

void CavaService::stop() {
    if (!m_proc) return;
    m_proc->disconnect(this);
    m_proc->terminate();
    if (!m_proc->waitForFinished(300)) m_proc->kill();
    m_proc->deleteLater();
    m_proc = nullptr;
    m_buffer.clear();
    // relax the bars to zero
    bool changed = false;
    for (auto &v : m_bars)
        if (v.toInt() != 0) {
            v = 0;
            changed = true;
        }
    if (changed) emit barsChanged();
}

void CavaService::onReadyRead() {
    if (!m_proc) return;
    m_buffer += m_proc->readAllStandardOutput();

    int nl = -1;
    QByteArray lastFrame;
    // keep only the most recent complete frame — we render at UI cadence
    while ((nl = m_buffer.indexOf('\n')) >= 0) {
        lastFrame = m_buffer.left(nl);
        m_buffer.remove(0, nl + 1);
    }
    if (lastFrame.isEmpty()) return;

    const QList<QByteArray> parts = lastFrame.split(';');
    if (parts.size() < m_barCount) return;
    for (int i = 0; i < m_barCount; ++i) {
        bool ok = false;
        const int v = parts.at(i).trimmed().toInt(&ok);
        m_bars[i] = ok ? qBound(0, v, 100) : 0;
    }
    emit barsChanged();
}

}  // namespace vespera
